version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "packages/mui-themes"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "packages/react"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "packages/style-dictionary"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "packages/styles"
    schedule:
      interval: "daily"
