version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "examples/vanilla"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "packages/react"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "packages/react-storybook"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "packages/react-unstyled"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "packages/styles"
    schedule:
      interval: "daily"
