---
name: facio_styles
description: Styles and assets for Facio Design System
version: 0.1.6
homepage: https://github.com/FacioCode/design/tree/master/packages/styles#readme
repository: https://github.com/FacioCode/design
issue_tracker: https://github.com/FacioCode/design/issues
documentation: https://github.com/FacioCode/design/tree/master/packages/styles#readme

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter: ~
