---
name: facio_styles
description: Facio Design System style package for use in Flutter applications. The styles in this package are consumed by the UI components of Facio applications built on Flutter.
version: 0.22.0
homepage: https://github.com/FacioCode/design/tree/main/packages/flutter-styles#readme
repository: https://github.com/FacioCode/design
issue_tracker: https://github.com/FacioCode/design/issues
documentation: https://github.com/FacioCode/design/tree/main/packages/flutter-styles#readme

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

# The following section is specific to Flutter.
flutter: ~
