---
name: {{pubspec.displayName}}
description: {{pubspec.description}}
version: {{pubspec.version}}
author: {{pubspec.author}}
homepage: {{pubspec.homepage}}
repository: {{pubspec.repository}}
issue_tracker: {{pubspec.bugs}}
documentation: {{pubspec.documentation}}
publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter: ~
