export const backgroundDefault = "#ffffff";
export const backgroundPaper = "#ffffff"; // Useful for app bars
export const backgroundShadedPaper = "#fafafa"; // Useful for grey containers, table headers and and odd table rows on web
export const backgroundDarkShadedPaper = "#f2f2f3"; // Useful for input background, for example
export const backgroundRowHover = "#e3eeff";
export const backgroundAlertFilledError = "#ffb3cc";
export const backgroundAlertFilledInfo = "#b3ccff";
export const backgroundAlertFilledWarning = "#ffe6b3";
export const backgroundAlertStandardError = "#ffe3ee";
export const backgroundAlertStandardInfo = "#e3eeff";
export const backgroundAlertStandardWarning = "#fff4e3";
export const backgroundAlertStandardNeutral = "#fafafa";
export const backgroundBrand = "#3fe1b6";
export const backgroundSelected = "#e3fcff";
export const baseErrorMain = "#c42b47";
export const baseErrorDark = "#890606";
export const baseInfoMain = "#066089";
export const baseInfoDark = "#002c5e";
export const basePrimaryLighter = "#d0ffef";
export const basePrimaryLight = "#53fec5";
export const basePrimaryMain = "#3fe1b6";
export const basePrimaryDark = "#2bc4a8";
export const baseSecondaryMain = "#424d5c";
export const baseSecondaryDark = "#303846";
export const baseWarningMain = "#fec553";
export const baseWarningDark = "#c4a82b";
export const baseTransparent30 = "rgba(33, 38, 49, 0.13)";
export const baseTransparent50 = "rgba(0, 0, 0, 0.5)"; // TODO: check this value
export const baseTransparent70 = "rgba(0, 15, 35, 0.74)";
export const baseTransparent00 = "rgba(255, 255, 255, 0)";
export const baseTransparent05 = "rgba(16, 22, 21, 0.02)";
export const baseGrey10 = "#f2f2f3";
export const baseGrey20 = "#ededee";
export const baseGrey30 = "#e2e3e4";
export const baseGrey40 = "#d1d3d6";
export const baseGrey50 = "#afb4bb";
export const baseGrey60 = "#828c9b";
export const baseGrey70 = "#424d5c";
export const baseGrey80 = "#303846";
export const baseGrey90 = "#1f252e";
export const baseGrey05 = "#fafafa";
export const baseAquamarine10 = "#d0ffef";
export const baseAquamarine20 = "#b3ffe6";
export const baseAquamarine30 = "#88ffd5";
export const baseAquamarine40 = "#53fec5";
export const baseAquamarine50 = "#3fe1b6";
export const baseAquamarine60 = "#2bc4a8";
export const baseAquamarine70 = "#05797d"; // Updated because of accessibility improvements
export const baseAquamarine80 = "#005c5e";
export const baseAquamarine90 = "#083f39";
export const baseAquamarine05 = "#e3fff4";
export const baseSkyBlue10 = "#d0f8ff";
export const baseSkyBlue20 = "#b3f2ff";
export const baseSkyBlue30 = "#88edff";
export const baseSkyBlue40 = "#53e2fe";
export const baseSkyBlue50 = "#3fbbe1";
export const baseSkyBlue60 = "#2b94c4";
export const baseSkyBlue70 = "#066089";
export const baseSkyBlue80 = "#002c5e";
export const baseSkyBlue90 = "#082a3f";
export const baseSkyBlue05 = "#e3fcff";
export const baseRoyalBlue10 = "#d0e0ff";
export const baseRoyalBlue20 = "#b3ccff";
export const baseRoyalBlue30 = "#88b2ff";
export const baseRoyalBlue40 = "#538cfe";
export const baseRoyalBlue50 = "#3f6ae1";
export const baseRoyalBlue60 = "#2b47c4";
export const baseRoyalBlue70 = "#0a0689";
export const baseRoyalBlue80 = "#02005e";
export const baseRoyalBlue90 = "#080e3f";
export const baseRoyalBlue05 = "#e3eeff";
export const baseIndianRed10 = "#ffd0e0";
export const baseIndianRed20 = "#ffb3cc";
export const baseIndianRed30 = "#ff88b2";
export const baseIndianRed40 = "#fe538c";
export const baseIndianRed50 = "#e13f6a";
export const baseIndianRed60 = "#c42b47";
export const baseIndianRed70 = "#890606";
export const baseIndianRed80 = "#5e0000";
export const baseIndianRed90 = "#3f080e";
export const baseIndianRed05 = "#ffe3ee";
export const baseGoldenrod10 = "#ffefd0";
export const baseGoldenrod20 = "#ffe6b3";
export const baseGoldenrod30 = "#ffd588";
export const baseGoldenrod40 = "#fec553";
export const baseGoldenrod50 = "#e1b63f";
export const baseGoldenrod60 = "#c4a82b";
export const baseGoldenrod70 = "#858906";
export const baseGoldenrod80 = "#5c5e00";
export const baseGoldenrod90 = "#3f3908";
export const baseGoldenrod05 = "#fff4e3";
export const baseWhite = "#ffffff";
export const baseBlack = "#1f252e";
export const borderOutlinedButtonPressed = "#2bc4a8";
export const borderOutlinedButtonFocus = "#3fbbe1"; // Useful for focused contained button
export const borderOutlinedButtonHover = "#3fe1b6";
export const borderFocus = "#53e2fe"; // Useful for outlined and link button
export const borderDivider = "#e2e3e4"; // It must be a value that offers good/sufficient contrast for white backgrounds
export const fontHeadline1 = "#1f252e";
export const fontPrimaryHighContrast = "#303846"; // Font color for warning button and some typography variants
export const fontPrimary = "#424d5c"; // Color for label, card, input base, paper, body text and another typographies
export const fontSecondary = "#828c9b"; // Font color for disabled contained button font. Better for contrast.
export const fontDisabled = "#afb4bb"; // Font color for disabled outlined button, disabled link button.
export const fontPlaceholder = "#afb4bb"; // Useful for text field placeholders
export const fontHint = "#afb4bb"; // Font/icon color for hint texts
export const fontInverse = "#ffffff";
export const fontError = "#c42b47"; // Useful for error/danger messages
export const fontLink = "#05797d";
export const fontLinkPressed = "#005c5e";
export const inputChecked = "#424d5c";
export const inputDefault = "#828c9b";
export const inputDisabled = "#afb4bb";
export const inputSwitchBase = "#fafafa";
export const inputSwitchTrack = "#afb4bb";