export const alertIconMarginRight = "8px";
export const alertRootBorderRadius = "8px";
export const alertStandardInfoBackgroundColor = "#b3ccff";
export const alertStandardBrandBackgroundColor = "#3fe1b6";
export const appBarColorDefaultBackgroundColor = "#f2f2f3";
export const appBarRootHeight = "56px"; // Specific AppBar height for web
export const buttonRootMaxWidth = 600;
export const buttonRootMinWidth = "64px";
export const buttonFullWidthBorderRadius = "8px";
export const buttonLabelFontSize = "0.875rem"; // Default button font size can vary depending on platform.
export const buttonLabelFontWeight = 600; // Medium button labels have semi bold font weight
export const buttonSizeSmallHeight = "32px";
export const buttonSizeSmallPaddingBottom = "4px";
export const buttonSizeSmallPaddingLeft = "12px"; // All small buttons have left padding equivalent to 4 logical pixels
export const buttonSizeSmallPaddingRight = "12px"; // All small buttons have right padding equivalent to 4 logical pixels
export const buttonSizeSmallPaddingTop = "4px";
export const buttonSizeMediumHeight = "48px";
export const buttonSizeMediumPaddingBottom = "12px";
export const buttonSizeMediumPaddingTop = "12px";
export const cardContentRootPadding = "16px";
export const cardRootBackgroundColor = "#fafafa";
export const cardRootBorderRadius = "8px";
export const cardRootColor = "#424d5c";
export const cardRootMarginBottom = "24px";
export const cardRootMarginLeft = "16px";
export const cardRootMarginRight = "16px";
export const cardRootMarginTop = "0px";
export const checkboxRootColor = "#828c9b";
export const checkboxCheckedColor = "#424d5c";
export const checkboxDisabledColor = "#afb4bb";
export const chipRootBorderRadius = "16px";
export const chipRootBorderWidth = "1px";
export const chipRootHeight = "32px";
export const containedButtonRootBorderWidth = "0px";
export const containedButtonHoverBoxShadow = "#d1d3d6";
export const containedButtonBrandBackgroundColor = "#3fe1b6";
export const containedButtonBrandColor = "#424d5c";
export const containedButtonBrandHoverBackgroundColor = "#3fe1b6";
export const containedButtonBrandHoverColor = "#424d5c";
export const containedButtonBrandPressedBackgroundColor = "#2bc4a8";
export const containedButtonBrandPressedColor = "#424d5c";
export const containedButtonDangerBackgroundColor = "#e13f6a";
export const containedButtonDangerColor = "#ffffff";
export const containedButtonDangerHoverBackgroundColor = "#e13f6a";
export const containedButtonDangerHoverColor = "#ffffff";
export const containedButtonDangerPressedBackgroundColor = "#c42b47";
export const containedButtonDangerPressedColor = "#ffffff";
export const containedButtonDefaultBackgroundColor = "#424d5c";
export const containedButtonDefaultColor = "#ffffff";
export const containedButtonDefaultHoverBackgroundColor = "#424d5c";
export const containedButtonDefaultHoverColor = "#ffffff";
export const containedButtonDefaultPressedBackgroundColor = "#303846";
export const containedButtonDefaultPressedColor = "#ffffff";
export const containedButtonSizeMediumBorderRadius = "24px";
export const containedButtonSizeSmallBorderRadius = "16px";
export const containedButtonWarningBackgroundColor = "#e1b63f";
export const containedButtonWarningColor = "#ffffff";
export const containedButtonWarningHoverBackgroundColor = "#e1b63f";
export const containedButtonWarningHoverColor = "#ffffff";
export const containedButtonWarningPressedBackgroundColor = "#c4a82b";
export const containedButtonWarningPressedColor = "#ffffff";
export const inputBaseRootColor = "#424d5c";
export const inputBaseRootLineHeight = "1.4375em"; // 23px
export const inputBaseMediumFontSize = "1rem"; // Font size is the same of headline, formerly headline.
export const inputBaseInputBorder = "0px";
export const inputBaseInputHeight = "1.4375em"; // Reset 23px the native input line-height
export const inputBaseInputMargin = "0px";
export const inputBaseInputMinWidth = "0px"; // Make the flex item shrink with Firefox
export const inputBaseInputPaddingTop = "4px";
export const inputBaseInputPaddingRight = "0px";
export const inputBaseInputPaddingBottom = "5px";
export const inputBaseInputPaddingLeft = "0px";
export const inputBaseLargeFontSize = "1.75em"; // At web, 1.75em = 28px (inspired on Flutter largeInput size)
export const labelLargeFontSize = "1rem"; // Font size is the same of subtitle1, formerly subhead.
export const labelMediumFontSize = "0.75rem"; // Font size is the same of caption.
export const linkButtonDefaultColor = "#068589";
export const linkButtonSizeSmallBorderRadius = "8px";
export const outlinedButtonRootBorderWidth = "1px";
export const outlinedButtonDefaultBorderColor = "#e2e3e4";
export const outlinedButtonDefaultColor = "#424d5c";
export const outlinedButtonDisabledColor = "#afb4bb";
export const outlinedButtonPressedBorderColor = "#2bc4a8";
export const outlinedButtonPressedColor = "#424d5c";
export const outlinedButtonHoverBorderColor = "#3fe1b6";
export const outlinedButtonSizeSmallBorderRadius = "16px";
export const outlinedButtonSizeSmallPaddingBottom = "2px";
export const outlinedButtonSizeSmallPaddingTop = "2px";
export const outlinedButtonSizeMediumBorderRadius = "8px";
export const paperRootBackgroundColor = "#fafafa";
export const paperRootColor = "#424d5c";
export const paperRoundedBorderRadius = "8px";
export const paperSquareBorderRadius = "0px";
export const typographyHeadline1Color = "#1f252e";
export const typographyHeadline1FontFamily = "Open Sans, sans-serif";
export const typographyHeadline1FontSize = "3.38888889rem"; // Extremely large text. It is the most prominent element in the interface.
export const typographyHeadline1FontWeight = 800; // We use extra bold everytime we want to show monetary info.
export const typographyHeadline1LetterSpacing = "-4px";
export const typographyHeadline1LineHeight = "1.32786885em";
export const typographyHeadline1MarginBottom = "0.8852459em";
export const typographyHeadline1MarginTop = "0.44262295em";
export const typographyHeadline2Color = "#303846";
export const typographyHeadline2FontFamily = "Open Sans, sans-serif";
export const typographyHeadline2FontSize = "2.27777778rem"; // Very, very large text
export const typographyHeadline2FontWeight = 700;
export const typographyHeadline2LetterSpacing = "-2px";
export const typographyHeadline2LineHeight = "1.31707317em";
export const typographyHeadline2MarginBottom = "1em";
export const typographyHeadline2MarginTop = "1em";
export const typographyHeadline3Color = "#303846";
export const typographyHeadline3FontFamily = "Open Sans, sans-serif";
export const typographyHeadline3FontSize = "1.5rem"; // Very large text
export const typographyHeadline3FontWeight = 700;
export const typographyHeadline3LetterSpacing = "-1px";
export const typographyHeadline3LineHeight = "1em";
export const typographyHeadline3MarginBottom = "1em";
export const typographyHeadline3MarginTop = "1em";
export const typographyHeadline4Color = "#303846";
export const typographyHeadline4FontFamily = "Open Sans, sans-serif";
export const typographyHeadline4FontSize = "1rem"; // Large text
export const typographyHeadline4FontWeight = 700;
export const typographyHeadline4LetterSpacing = "0.25px";
export const typographyHeadline4LineHeight = "1.5em";
export const typographyHeadline4MarginBottom = "0em";
export const typographyHeadline4MarginTop = "1em";
export const typographyHeadline5Color = "#303846";
export const typographyHeadline5FontFamily = "Open Sans, sans-serif";
export const typographyHeadline5FontSize = "1rem"; // Recommended for large text in dialogs.
export const typographyHeadline5FontWeight = 700;
export const typographyHeadline5LetterSpacing = "0px";
export const typographyHeadline5LineHeight = "1.5em";
export const typographyHeadline5MarginBottom = "0em";
export const typographyHeadline5MarginTop = "1.5em";
export const typographyBodyText1Color = "#424d5c";
export const typographyBodyText1FontFamily = "Open Sans, sans-serif";
export const typographyBodyText1FontSize = "1rem";
export const typographyBodyText1FontWeight = 400;
export const typographyBodyText1LetterSpacing = "0px";
export const typographyBodyText1LineHeight = "1.5em";
export const typographyBodyText1MarginBottom = "1.5em";
export const typographySubtitle1Color = "#303846";
export const typographySubtitle1FontFamily = "Open Sans, sans-serif";
export const typographySubtitle1FontSize = "1rem"; // A little smaller than headline5.
export const typographySubtitle1FontWeight = 600;
export const typographySubtitle1LetterSpacing = "0px";
export const typographySubtitle1LineHeight = "1.5em";
export const typographySubtitle2Color = "#424d5c";
export const typographySubtitle2FontFamily = "Open Sans, sans-serif";
export const typographySubtitle2FontSizeFontSize = "1rem";
export const typographySubtitle2FontWeight = 400;
export const typographySubtitle2LetterSpacing = "0px";
export const typographySubtitle2LineHeight = "1.5em";
export const typographyButtonColor = "#424d5c"; // Button color is secondary (probably grey-80) by default
export const typographyButtonFontFamily = "Open Sans, sans-serif";
export const typographyButtonFontSize = "0.875rem";
export const typographyButtonFontWeight = 600;
export const typographyButtonLetterSpacing = "0px";
export const typographyBodyText2Color = "#424d5c";
export const typographyBodyText2FontFamily = "Open Sans, sans-serif";
export const typographyBodyText2FontSize = "0.875rem"; // Low emphasis, useful for very small blocks
export const typographyBodyText2FontWeight = 400;
export const typographyBodyText2LetterSpacing = "-0.15px";
export const typographyBodyText2LineHeight = "1.5em";
export const typographyCaptionColor = "#303846"; // Caption color is secondary (probably grey-80) by default
export const typographyCaptionFontFamily = "Open Sans, sans-serif";
export const typographyCaptionFontSize = "0.75rem"; // The smallest font size.
export const typographyCaptionFontWeight = 400;
export const typographyCaptionLetterSpacing = "0px";
export const typographyCaptionLineHeight = "1em";
export const typographyRootFontFamily = "Open Sans, sans-serif";
export const typographyRootMargin = "0px";
export const typographyHeadline6MarginBottom = "0em"; // Reuse margin bottom from headline5
export const typographyHeadline6MarginTop = "1.5em"; // Reuse margin top from headline5
export const baselineBackdropBackgroundColor = "#f2f2f3";
export const baselineBodyBackgroundColor = "#f2f2f3";
export const baselineBodyColor = "#424d5c";
export const baselineBodyFontFamily = "Open Sans, sans-serif";
export const baselineBodyFontSize = "1rem";
export const baselineBodyFontWeight = 400;
export const baselineBodyLineHeight = "1.5em";
export const baselineBodyMargin = "0px";
export const baselineBoldFontWeight = 700;
export const baselineHtmlFontSize = "1rem";
export const baselineHtmlLineHeight = "1.5em";
export const baselineMediaPrintBackgroundColor = "#ffffff"; // Intentionally using white color.
export const buttonBaseRootBorderRadius = "0px";
export const buttonBaseRootBorderWidth = "0px";
export const buttonBaseRootMargin = "0px"; // Remove the margin in Safari
export const buttonBaseRootOutline = "0px"; // Outline CSS prop. Disable the focus ring for mouse, touch and keyboard users
export const buttonBaseRootPadding = "0px";
export const currencyRootFontFamily = "'SF Mono', 'Monaco', 'Inconsolata', 'Fira Mono', 'Droid Sans Mono', 'Source Code Pro', monospace";
export const dialogActionsPaddingBottom = "48px";
export const dialogActionsPaddingLeft = "32px";
export const dialogActionsPaddingRight = "32px";
export const dialogActionsPaddingTop = "8px";
export const dialogActionsSpacingChildrenMarginLeft = "12px";
export const dialogContentPaddingBottom = "8px";
export const dialogContentPaddingLeft = "32px";
export const dialogContentPaddingRight = "32px";
export const dialogContentTextMarginBottom = "12px";
export const dialogPaperBackgroundColor = "#fafafa";
export const dialogPaperBorderRadius = "8px";
export const dialogPaperWidthSmMaxWidth = 600;
export const dialogTitlePaddingLeft = "32px";
export const dialogTitlePaddingRight = "32px";
export const formLabelRootLineHeight = "1em";
export const formLabelRootPadding = "0px";
export const tableCellRootBorderBottomColor = "#e2e3e4";
export const tableCellRootBorderBottomWidth = "1px";
export const tableRowSelectedBackgroundColor = "#e3fcff";