export const appBarRootHeight = "56px";
export const appBarColorDefaultBackgroundColor = "#ffffff";
export const buttonContainedBorderWidth = "0px";
export const buttonLabelColor = "#303846";
export const buttonLabelFontSize = "1rem"; // Default button font size can vary depending on platform.
export const buttonSizeMediumBorderRadius = "16px";
export const buttonSizeMediumFontWeight = 600; // Medium button labels have semi bold font weight
export const buttonSizeMediumHeight = "32px";
export const buttonSizeMediumLabelPaddingBottom = "4px";
export const buttonSizeMediumLabelPaddingTop = "4px";
export const buttonSizeLargeBorderRadius = "8px";
export const buttonSizeLargeFontWeight = 700; // Large button labels have bold font weight
export const buttonSizeLargeHeight = "48px";
export const buttonSizeLargeLabelPaddingBottom = "12px";
export const buttonSizeLargeLabelPaddingTop = "12px";
export const cardRootBorderRadius = "8px";
export const cardRootPadding = "16px";
export const cardDefaultBackgroundColor = "#ffffff";
export const cardDefaultColor = "#424d5c";
export const cardInfoBackgroundColor = "#b3ccff";
export const chipRootBorderRadius = "16px";
export const chipRootBorderWidth = "1px";
export const inputRootColor = "#424d5c";
export const inputRootLineHeight = "1.4375em"; // 23px
export const inputMediumFontSize = "1rem"; // Font size is the same of headline, formerly headline.
export const inputInputBorderWidth = "0px";
export const inputInputHeight = "1.4375em"; // Reset 23px the native input line-height
export const inputInputMargin = "0px";
export const inputInputMinWidth = "0px"; // Make the flex item shrink with Firefox
export const inputInputPaddingTop = "4px";
export const inputInputPaddingRight = "0px";
export const inputInputPaddingBottom = "5px";
export const inputInputPaddingLeft = "0px";
export const inputLargeFontSize = "1.75em"; // At web, 1.75em = 28px (inspired on Flutter largeInput size)
export const labelLargeFontSize = "1rem"; // Font size is the same of subtitle1, formerly subhead.
export const labelMediumFontSize = "0.75rem"; // Font size is the same of caption.
export const paperRootBackgroundColor = "#ffffff";
export const paperRootColor = "#424d5c";
export const paperRoundedBorderRadius = "8px";
export const paperSquareBorderRadius = "0px";
export const typographyHeadline1Color = "#1f252e";
export const typographyHeadline1FontFamily = "Open Sans, sans-serif";
export const typographyHeadline1FontSize = "3.38888889rem"; // Extremely large text. It is the most prominent element in the interface.
export const typographyHeadline1FontWeight = 800; // We use extra bold everytime we want to show monetary info.
export const typographyHeadline1LetterSpacing = "-4px";
export const typographyHeadline1LineHeight = "1.32786885em";
export const typographyHeadline1MarginBottom = "0.8852459em";
export const typographyHeadline1MarginTop = "0.44262295em";
export const typographyHeadline2Color = "#303846";
export const typographyHeadline2FontFamily = "Open Sans, sans-serif";
export const typographyHeadline2FontSize = "2.27777778rem"; // Very, very large text
export const typographyHeadline2FontWeight = 700;
export const typographyHeadline2LetterSpacing = "-2px";
export const typographyHeadline2LineHeight = "1.31707317em";
export const typographyHeadline2MarginBottom = "1em";
export const typographyHeadline2MarginTop = "1em";
export const typographyHeadline3Color = "#303846";
export const typographyHeadline3FontFamily = "Open Sans, sans-serif";
export const typographyHeadline3FontSize = "1.5rem"; // Very large text
export const typographyHeadline3FontWeight = 700;
export const typographyHeadline3LetterSpacing = "-1px";
export const typographyHeadline3LineHeight = "1em";
export const typographyHeadline3MarginBottom = "1em";
export const typographyHeadline3MarginTop = "1em";
export const typographyHeadline4Color = "#303846";
export const typographyHeadline4FontFamily = "Open Sans, sans-serif";
export const typographyHeadline4FontSize = "1rem"; // Large text
export const typographyHeadline4FontWeight = 700;
export const typographyHeadline4LetterSpacing = "0.25px";
export const typographyHeadline4LineHeight = "1.5em";
export const typographyHeadline4MarginBottom = "0em";
export const typographyHeadline4MarginTop = "1em";
export const typographyHeadline5Color = "#303846";
export const typographyHeadline5FontFamily = "Open Sans, sans-serif";
export const typographyHeadline5FontSize = "1rem"; // Recommended for large text in dialogs.
export const typographyHeadline5FontWeight = 700;
export const typographyHeadline5LetterSpacing = "0px";
export const typographyHeadline5LineHeight = "1.5em";
export const typographyHeadline5MarginBottom = "0em";
export const typographyHeadline5MarginTop = "1.5em";
export const typographyBodyText1Color = "#424d5c";
export const typographyBodyText1FontFamily = "Open Sans, sans-serif";
export const typographyBodyText1FontSize = "1rem";
export const typographyBodyText1FontWeight = 400;
export const typographyBodyText1LetterSpacing = "0px";
export const typographyBodyText1LineHeight = "1.5em";
export const typographyBodyText1MarginBottom = "1.5em";
export const typographySubtitle1Color = "#303846";
export const typographySubtitle1FontFamily = "Open Sans, sans-serif";
export const typographySubtitle1FontSize = "1rem"; // A little smaller than headline5.
export const typographySubtitle1FontWeight = 700;
export const typographySubtitle1LetterSpacing = "0px";
export const typographySubtitle1LineHeight = "1.5em";
export const typographySubtitle2Color = "#424d5c";
export const typographySubtitle2FontFamily = "Open Sans, sans-serif";
export const typographySubtitle2FontSizeFontSize = "1rem";
export const typographySubtitle2FontWeight = 400;
export const typographySubtitle2LetterSpacing = "0px";
export const typographySubtitle2LineHeight = "1.5em";
export const typographyButtonColor = "#303846"; // Button color is secondary (probably grey-80) by default
export const typographyButtonFontFamily = "Open Sans, sans-serif";
export const typographyButtonFontSize = "1rem";
export const typographyButtonLetterSpacing = "0px";
export const typographyBodyText2Color = "#424d5c";
export const typographyBodyText2FontFamily = "Open Sans, sans-serif";
export const typographyBodyText2FontSize = "0.875rem"; // Low emphasis, useful for very small blocks
export const typographyBodyText2FontWeight = 400;
export const typographyBodyText2LetterSpacing = "-0.15px";
export const typographyBodyText2LineHeight = "1.5em";
export const typographyCaptionColor = "#303846"; // Caption color is secondary (probably grey-80) by default
export const typographyCaptionFontFamily = "Open Sans, sans-serif";
export const typographyCaptionFontSize = "0.75rem"; // The smallest font size.
export const typographyCaptionFontWeight = 400;
export const typographyCaptionLetterSpacing = "0px";
export const typographyCaptionLineHeight = "1em";
export const typographyRootMargin = "0px";
export const typographyHeadline6MarginBottom = "0em"; // Reuse margin bottom from headline5
export const typographyHeadline6MarginTop = "1.5em"; // Reuse margin top from headline5
export const typographyAlignLeftTextAlign = "leftem";
export const typographyAlignCenterTextAlign = "centerem";
export const typographyAlignRightTextAlign = "rightem";
export const baselineBackdropBackgroundColor = "#ffffff";
export const baselineBodyBackgroundColor = "#ffffff";
export const baselineBodyColor = "#424d5c";
export const baselineBodyFontFamily = "Open Sans, sans-serif";
export const baselineBodyFontSize = "1rem";
export const baselineBodyFontWeight = 400;
export const baselineBodyLineHeight = "1.5em";
export const baselineBodyMargin = "0px";
export const baselineBoldFontWeight = 700;
export const baselineHtmlFontSize = "1rem";
export const baselineHtmlLineHeight = "1.5em";
export const baselineMediaPrintColor = "#ffffff";