export const baseNone = "0px";
export const baseOne = "1px";
export const baseQuarter = "2px";
export const baseFocus = "3px";
export const baseHalf = "4px";
export const baseHalfQuarter = "6px"; // Commonly used for small button vertical padding
export const baseSingle = "8px";
export const baseSingleHalf = "12px"; // Commonly used for medium button vertical padding or dialog content text margin
export const baseDouble = "16px"; // Twice the base value (8) = 16
export const baseDoubleQuarter = "18px"; // New border radius for small buttons
export const baseDoubleHalf = "20px"; // Commonly used for switch thumb dimensions
export const baseTriple = "24px"; // Commonly used for button label height
export const baseTripleHalf = "28px"; // Used for medium input top padding
export const baseQuadruple = "32px"; // Formerly used for small button height.
export const baseQuadrupleHalf = "36px"; // After some experiments, this is the new small button size
export const baseFivefold = "40px"; // Used for large input height
export const baseSixfold = "48px";
export const baseSevenfold = "56px"; // Commonly used for app bar height
export const baseEightfold = "64px"; // Commonly used for button min height
export const baseNinefold = "72px"; // Commonly used for bottom sheet min height
export const baseFifteenFold = "120px"; // Useful for Brazilian CPF XGrid columns
export const baseEighteenFold = "144px"; // Useful for Date and Time XGrid columns
export const baseTwentyFourFold = "192px"; // Useful for Cancellation Reason XGrid columns
export const baseThirtyOneFold = "248px"; // Button max width
export const baseHalfPlusOne = "5px"; // Reserved for input padding for web (4+1)