---
name: facio_design_system
description: Facio Design System style tokens and UI components for Facio applications built on Flutter.
version: 9.0.1
homepage: https://github.com/FacioCode/design/tree/main/packages/flutter#readme
repository: https://github.com/FacioCode/design
issue_tracker: https://github.com/FacioCode/design/issues
documentation: https://github.com/FacioCode/design/tree/main/packages/flutter#readme

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: ">=1.22.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: "Facio Icons"
      fonts:
        - asset: "assets/fonts/FacioIcons.ttf"
          style: "normal"
          weight: 400
    - family: "Open Sans"
      fonts:
        - asset: "assets/fonts/OpenSans-Light.ttf"
          style: "normal"
          weight: 300
        - asset: "assets/fonts/OpenSans-LightItalic.ttf"
          style: "italic"
          weight: 300
        - asset: "assets/fonts/OpenSans-Regular.ttf"
          style: "normal"
          weight: 400
        - asset: "assets/fonts/OpenSans-RegularItalic.ttf"
          style: "italic"
          weight: 400
        - asset: "assets/fonts/OpenSans-SemiBold.ttf"
          style: "normal"
          weight: 600
        - asset: "assets/fonts/OpenSans-SemiBoldItalic.ttf"
          style: "italic"
          weight: 600
        - asset: "assets/fonts/OpenSans-Bold.ttf"
          style: "normal"
          weight: 700
        - asset: "assets/fonts/OpenSans-BoldItalic.ttf"
          style: "italic"
          weight: 700
        - asset: "assets/fonts/OpenSans-ExtraBold.ttf"
          style: "normal"
          weight: 800
        - asset: "assets/fonts/OpenSans-ExtraBoldItalic.ttf"
          style: "italic"
          weight: 800