part of facio_styles;

class Sizes {
  Sizes._();

  static const baseDouble = 16.00;
  static const baseFivefold = 40.00;
  static const baseHalf = 4.00;
  static const baseNone = 0.00;
  static const baseOne = 1.00;
  static const baseQuadruple = 32.00;
  static const baseQuarter = 2.00;
  static const baseSevenfold = 56.00;
  static const baseSingle = 8.00;
  static const baseSingleHalf = 12.00;
  static const baseSixfold = 48.00;
  static const baseTriple = 24.00;
  static const borderRadiusDouble = 16.00;
  static const borderRadiusNone = 0.00;
  static const borderRadiusSingle = 8.00;
  static const borderWidthNone = 0.00;
  static const borderWidthSingle = 1.00;
  static const fontBaseFontSize = 17.00;
  static const fontBaseLetterSpacing = -0.43;
  static const fontBaseLineHeight = 24.00;
  static const fontBodyText1FontSize = 17.00;
  static const fontBodyText1LetterSpacing = -0.43;
  static const fontBodyText1LineHeight = 24.00;
  static const fontBodyText2FontSize = 14.00;
  static const fontBodyText2LetterSpacing = -0.15;
  static const fontBodyText2LineHeight = 24.00;
  static const fontButtonFontSize = 14.00;
  static const fontButtonLetterSpacing = -0.15;
  static const fontButtonLineHeight = 24.00;
  static const fontCaptionFontSize = 12.00;
  static const fontCaptionLetterSpacing = 0.00;
  static const fontCaptionLineHeight = 16.00;
  static const fontHeadline1FontSize = 34.00;
  static const fontHeadline1LetterSpacing = -0.50;
  static const fontHeadline1LineHeight = 40.00;
  static const fontHeadline2FontSize = 28.00;
  static const fontHeadline2LetterSpacing = -0.38;
  static const fontHeadline2LineHeight = 40.00;
  static const fontHeadline3FontSize = 22.00;
  static const fontHeadline3LetterSpacing = -0.26;
  static const fontHeadline3LineHeight = 32.00;
  static const fontHeadline4FontSize = 20.00;
  static const fontHeadline4LetterSpacing = -0.45;
  static const fontHeadline4LineHeight = 24.00;
  static const fontHeadline5FontSize = 17.00;
  static const fontHeadline5LetterSpacing = -0.43;
  static const fontHeadline5LineHeight = 24.00;
  static const fontSubtitleFontSize = 15.00;
  static const fontSubtitleLetterSpacing = -0.23;
  static const fontSubtitleLineHeight = 24.00;
}
