name: Bump version and create GitHub release

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --global --loglevel=error lerna
    - run: npm ci
    - run: git config --global user.email "technology+opensource@facio.com"
    - run: git config --global user.name "Facio"
    - run: lerna version --conventional-commits --create-release github --yes
      env:
        GH_TOKEN: ${{secrets.gh_token}}
        GH_AUTH_TOKEN: ${{secrets.gh_auth_token}}
    - run: git add packages/flutter-styles/pubspec.yaml
    - run: "git commit --allow-empty -m \"chore(flutter-styles): update pubspec version [skip ci]\""
    - run: git push
