name: Publish packages

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Fetch git branches
        run: git fetch
      - name: Checkout main branch
        run: git checkout main
      - name: Install dependencies
        run: npm ci --no-optional
      - name: Build and run tests
        run: npm test
      - name: Set git author identity
        run: sh ./.github/scripts/configure-git.sh
      - name: Bump pubspec version
        run: sh ./.github/scripts/bump-pubspec.sh
      - name: Cache dist/ folders
        uses: actions/cache@v2
        env:
          cache-name: cache-dist-folders
        with:
          path: |
            packages/*/dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/*/dist/index.js') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Cache pubspec file
        uses: actions/cache@v2
        env:
          cache-name: cache-pubspec-file
        with:
          path: |
            packages/flutter_ds/pubspec.yaml
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/flutter_ds/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

  publish-node-packages:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Restore cached output
        uses: actions/cache@v2
        env:
          cache-name: cache-dist-folders
        with:
          path: |
            packages/*/dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/*/dist/index.js') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: List dist/ folders
        run: ls packages/*/dist
      - name: Prepare for npm publishing
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install Lerna globally
        run: npm install -g lerna
      - name: Checking npm credentials
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Set git author identity
        run: sh ./.github/scripts/configure-git.sh
      - name: Publish to npm
        run: lerna publish from-git --ignore-prepublish --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Prepare for GitHub Packages publishing
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
      - name: Publish to GitHub Packages
        run: lerna publish from-got --ignore-prepublish --registry https://npm.pkg.github.com/ --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish-pubdev-package:
    if: ${{ false }} # TODO: re-enable after fixing null safety package error
    needs: build
    runs-on: ubuntu-latest
    env:
      working-directory: ./packages/flutter_ds
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Restore cached output
        uses: actions/cache@v2
        env:
          cache-name: cache-pubspec-file
        with:
          path: |
            packages/flutter_ds/pubspec.yaml
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/flutter_ds/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.0"
      - name: Setup pub credentials
        run: |
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.PUB_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.PUB_REFRESH_TOKEN }}",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
            "expiration": 1606086594822
          }
          EOF
      - name: Install project dependencies
        run: flutter pub get
        working-directory: ${{env.working-directory}}
      - name: Format files
        run: dartfmt -w .
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
        working-directory: ${{env.working-directory}}
      - name: Analyze project source
        run: dart analyze --fatal-infos
        working-directory: ${{env.working-directory}}
      - name: Ensure Example builds
        run: flutter build appbundle -t lib/main.dart
        working-directory: ${{env.working-directory}}/example
      - name: Publish package
        run: pub publish -f
        working-directory: ${{env.working-directory}}
