name: Publish packages
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure git author identity
        run: sh ./.github/scripts/configure-git.sh
      - name: Fetch git branches
        run: git fetch
      - name: Checkout main branch
        run: git checkout main
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - name: Install npm v7.19.1
        # npm >= 7.20 breaks when installing workspace packages
        run: npm install -g npm@7.19.1
      - name: Check npm version
        run: npm -v
      - name: Cache dist/ folders and pubspec file
        uses: actions/cache@v2
        env:
          cache-name: dist-folders
        with:
          path: |
            packages/*/dist
            packages/flutter_ds/pubspec.yaml
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('packages/*/dist/index.js') }}
      - name: Cache pubspec file
        uses: actions/cache@v2
        env:
          cache-name: pubspec-file
        with:
          path: |
            packages/flutter_ds/pubspec.yaml
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('packages/flutter_ds/pubspec.yaml') }}
      - name: Install dependencies
        run: npm ci --no-optional
      - name: Build and run tests
        run: npm test
      - name: Bump pubspec version
        run: sh ./.github/scripts/bump-pubspec.sh
      - name: List dist/ folders
        run: ls packages/*/dist
      - name: Checking npm credentials
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Publish to npm
        run: npm run publish-packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Prepare for GitHub Packages publishing
        uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "16"
          registry-url: "https://npm.pkg.github.com"
      - name: Publish to GitHub Packages
        run: npm run publish-packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
