name: Publish packages
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure git author identity
        run: sh ./.github/scripts/configure-git.sh
      - name: Fetch git branches
        run: git fetch
      - name: Checkout main branch
        run: git checkout main
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - name: Install npm v7.19.1
        # npm >= 7.20 breaks when installing workspace packages
        run: npm install -g npm@7.19.1
      - name: Check npm version
        run: npm -v
      - name: Cache dist/ folders
        uses: actions/cache@v2
        env:
          cache-name: cache-dist-folders
        with:
          path: |
            packages/*/dist
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('packages/*/dist/index.js') }}
      - name: Cache pubspec file
        uses: actions/cache@v2
        env:
          cache-name: cache-pubspec-file
        with:
          path: |
            packages/flutter_ds/pubspec.yaml
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('packages/flutter_ds/pubspec.yaml') }}
      - name: Install dependencies
        run: npm ci --no-optional
      - name: Build and run tests
        run: npm test
      - name: Bump pubspec version
        run: sh ./.github/scripts/bump-pubspec.sh
      - name: List dist/ folders
        run: ls packages/*/dist
      - name: Checking npm credentials
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Publish to npm
        run: npm run publish-packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Prepare for GitHub Packages publishing
        uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "16"
          registry-url: "https://npm.pkg.github.com"
      - name: Publish to GitHub Packages
        run: npm run publish-packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  publish-pubdev-package:
    env:
      working-directory: ./packages/flutter_ds
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Restore cached output
        uses: actions/cache@v2
        env:
          cache-name: cache-pubspec-file
        with:
          path: |
            packages/flutter_ds/pubspec.yaml
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('packages/flutter_ds/pubspec.yaml') }}
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.5"
      # Credentials can be generated by running `flutter packages pub login` in your dev env.
      - name: Setup pub credentials
        run: |
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.PUB_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.PUB_REFRESH_TOKEN }}",
            "idToken":"${{ secrets.PUB_ID_TOKEN }}",
            "tokenEndpoint":"${{ secrets.PUB_TOKEN_ENDPOINT }}",
            "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
            "expiration": ${{ secrets.PUB_EXPIRATION }}
          }
          EOF
      - name: Install project dependencies
        run: flutter pub get
        working-directory: ${{env.working-directory}}
      - name: Format files
        run: dartfmt -w .
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
        working-directory: ${{env.working-directory}}
      - name: Analyze project source
        run: dart analyze --fatal-infos
        working-directory: ${{env.working-directory}}
      - name: Ensure Example builds
        run: flutter build appbundle -t lib/main.dart
        working-directory: ${{env.working-directory}}/example
      - name: Publish package
        run: pub publish -f
        working-directory: ${{env.working-directory}}
