name: Pull request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Install npm v7.19.1
        # npm >= 7.20 breaks when installing workspace packages
        run: npm install -g npm@7.19.1
      - name: Check npm version
        run: npm -v
      - name: Install project dependencies
        run: npm ci --no-optional
      - name: Run tests
        run: npm test
