name: Node.js Packages version bump

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Pull all tags for Lerna semantic release
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "16"
      # @see https://github.com/npm/cli/issues/2231
      - name: Install latest version of npm
        run: npm install -g npm
      - name: Install Lerna globally
        run: npm install -g lerna
      - name: Run Lerna bootstrap
        run: npm run bootstrap
      - name: Install project dependencies
        run: npm ci --no-optional
      - name: Set git author identity
        run: sh ./.github/scripts/configure-git.sh
      - name: Bump versions and create release
        run: lerna version --conventional-commits --create-release github --force-publish --yes
        env:
          GH_TOKEN: ${{secrets.gh_token}}
          GH_AUTH_TOKEN: ${{secrets.gh_auth_token}}
